{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Creating the Dataset\n",
    "\n",
    "A dataset is created with 20 columns and 20 rows, resembling survey data. Each column represents a question, and each row represents a respondent's answers."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# Create a larger dataset with 20 columns and 20 rows\n",
    "data = {\n",
    "    'Where do you live in Boston?': np.random.choice(['Downtown', 'Back Bay', 'South End', 'Beacon Hill', 'North End'], 20),\n",
    "    'How satisfied are you with the public transportation in your neighborhood?': np.random.choice(['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very Dissatisfied'], 20),\n",
    "    'How would you rate the safety in your neighborhood?': np.random.choice(['Very Safe', 'Safe', 'Neutral', 'Unsafe', 'Very Unsafe'], 20),\n",
    "    'How would you describe the cleanliness in your neighborhood?': np.random.choice(['Very Clean', 'Clean', 'Neutral', 'Dirty', 'Very Dirty'], 20),\n",
    "    'How would you rate the availability of amenities in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the quality of schools in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the affordability of housing in your neighborhood?': np.random.choice(['Very Affordable', 'Affordable', 'Neutral', 'Expensive', 'Very Expensive'], 20),\n",
    "    'How would you rate the friendliness of neighbors in your neighborhood?': np.random.choice(['Very Friendly', 'Friendly', 'Neutral', 'Unfriendly', 'Very Unfriendly'], 20),\n",
    "    'How satisfied are you with the green spaces in your neighborhood?': np.random.choice(['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very Dissatisfied'], 20),\n",
    "    'How would you rate the noise levels in your neighborhood?': np.random.choice(['Very Quiet', 'Quiet', 'Neutral', 'Noisy', 'Very Noisy'], 20),\n",
    "    'How would you rate the overall quality of life in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the public services in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the condition of roads and sidewalks in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the availability of parking in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the access to healthcare in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the quality of internet services in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the variety of restaurants in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the variety of shops in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the availability of cultural activities in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the availability of recreational activities in your neighborhood?': np.random.choice(['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'], 20),\n",
    "    'How would you rate the public transportation costs in your neighborhood?': np.random.choice(['Very Affordable', 'Affordable', 'Neutral', 'Expensive', 'Very Expensive'], 20)\n",
    "}\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Where do you live in Boston?</th>\n",
       "      <th>How satisfied are you with the public transportation in your neighborhood?</th>\n",
       "      <th>How would you rate the safety in your neighborhood?</th>\n",
       "      <th>How would you describe the cleanliness in your neighborhood?</th>\n",
       "      <th>How would you rate the availability of amenities in your neighborhood?</th>\n",
       "      <th>How would you rate the quality of schools in your neighborhood?</th>\n",
       "      <th>How would you rate the affordability of housing in your neighborhood?</th>\n",
       "      <th>How would you rate the friendliness of neighbors in your neighborhood?</th>\n",
       "      <th>How satisfied are you with the green spaces in your neighborhood?</th>\n",
       "      <th>How would you rate the noise levels in your neighborhood?</th>\n",
       "      <th>...</th>\n",
       "      <th>How would you rate the public services in your neighborhood?</th>\n",
       "      <th>How would you rate the condition of roads and sidewalks in your neighborhood?</th>\n",
       "      <th>How would you rate the availability of parking in your neighborhood?</th>\n",
       "      <th>How would you rate the access to healthcare in your neighborhood?</th>\n",
       "      <th>How would you rate the quality of internet services in your neighborhood?</th>\n",
       "      <th>How would you rate the variety of restaurants in your neighborhood?</th>\n",
       "      <th>How would you rate the variety of shops in your neighborhood?</th>\n",
       "      <th>How would you rate the availability of cultural activities in your neighborhood?</th>\n",
       "      <th>How would you rate the availability of recreational activities in your neighborhood?</th>\n",
       "      <th>How would you rate the public transportation costs in your neighborhood?</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Beacon Hill</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Affordable</td>\n",
       "      <td>Very Unfriendly</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Very Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Expensive</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Back Bay</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Dirty</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Unfriendly</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Neutral</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>South End</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Dirty</td>\n",
       "      <td>Average</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Affordable</td>\n",
       "      <td>Unfriendly</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Expensive</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>South End</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Safe</td>\n",
       "      <td>Clean</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Affordable</td>\n",
       "      <td>Unfriendly</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Good</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Good</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Downtown</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Unsafe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Affordable</td>\n",
       "      <td>Very Friendly</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Downtown</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Dirty</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Unfriendly</td>\n",
       "      <td>Dissatisfied</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Expensive</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>South End</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Safe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Expensive</td>\n",
       "      <td>Unfriendly</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Very Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Expensive</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Back Bay</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Unsafe</td>\n",
       "      <td>Dirty</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Expensive</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Dissatisfied</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Good</td>\n",
       "      <td>Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Back Bay</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Safe</td>\n",
       "      <td>Clean</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Affordable</td>\n",
       "      <td>Very Unfriendly</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Expensive</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>South End</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Very Safe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Average</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Affordable</td>\n",
       "      <td>Very Unfriendly</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>South End</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Clean</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Affordable</td>\n",
       "      <td>Very Unfriendly</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>...</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Neutral</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Back Bay</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Very Clean</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Affordable</td>\n",
       "      <td>Friendly</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Expensive</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Downtown</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Expensive</td>\n",
       "      <td>Unfriendly</td>\n",
       "      <td>Dissatisfied</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Back Bay</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Dirty</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Affordable</td>\n",
       "      <td>Very Friendly</td>\n",
       "      <td>Dissatisfied</td>\n",
       "      <td>Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Good</td>\n",
       "      <td>Good</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>South End</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Very Safe</td>\n",
       "      <td>Very Dirty</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Expensive</td>\n",
       "      <td>Friendly</td>\n",
       "      <td>Dissatisfied</td>\n",
       "      <td>Very Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Good</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Neutral</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Downtown</td>\n",
       "      <td>Very Dissatisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Dirty</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Affordable</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Beacon Hill</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Unsafe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Friendly</td>\n",
       "      <td>Dissatisfied</td>\n",
       "      <td>Very Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Beacon Hill</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Dirty</td>\n",
       "      <td>Good</td>\n",
       "      <td>Good</td>\n",
       "      <td>Very Expensive</td>\n",
       "      <td>Unfriendly</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Average</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Neutral</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>South End</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Very Unsafe</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Expensive</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Very Noisy</td>\n",
       "      <td>...</td>\n",
       "      <td>Good</td>\n",
       "      <td>Average</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Average</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Affordable</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>North End</td>\n",
       "      <td>Satisfied</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Clean</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Good</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Neutral</td>\n",
       "      <td>Very Satisfied</td>\n",
       "      <td>Quiet</td>\n",
       "      <td>...</td>\n",
       "      <td>Very Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Good</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Excellent</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Expensive</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>20 rows × 21 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   Where do you live in Boston?  \\\n",
       "0                   Beacon Hill   \n",
       "1                      Back Bay   \n",
       "2                     South End   \n",
       "3                     South End   \n",
       "4                      Downtown   \n",
       "5                      Downtown   \n",
       "6                     South End   \n",
       "7                      Back Bay   \n",
       "8                      Back Bay   \n",
       "9                     South End   \n",
       "10                    South End   \n",
       "11                     Back Bay   \n",
       "12                     Downtown   \n",
       "13                     Back Bay   \n",
       "14                    South End   \n",
       "15                     Downtown   \n",
       "16                  Beacon Hill   \n",
       "17                  Beacon Hill   \n",
       "18                    South End   \n",
       "19                    North End   \n",
       "\n",
       "   How satisfied are you with the public transportation in your neighborhood?  \\\n",
       "0                                   Very Dissatisfied                           \n",
       "1                                             Neutral                           \n",
       "2                                             Neutral                           \n",
       "3                                             Neutral                           \n",
       "4                                      Very Satisfied                           \n",
       "5                                      Very Satisfied                           \n",
       "6                                             Neutral                           \n",
       "7                                   Very Dissatisfied                           \n",
       "8                                             Neutral                           \n",
       "9                                           Satisfied                           \n",
       "10                                     Very Satisfied                           \n",
       "11                                     Very Satisfied                           \n",
       "12                                  Very Dissatisfied                           \n",
       "13                                     Very Satisfied                           \n",
       "14                                  Very Dissatisfied                           \n",
       "15                                  Very Dissatisfied                           \n",
       "16                                            Neutral                           \n",
       "17                                     Very Satisfied                           \n",
       "18                                          Satisfied                           \n",
       "19                                          Satisfied                           \n",
       "\n",
       "   How would you rate the safety in your neighborhood?  \\\n",
       "0                                         Very Unsafe    \n",
       "1                                         Very Unsafe    \n",
       "2                                             Neutral    \n",
       "3                                           Very Safe    \n",
       "4                                              Unsafe    \n",
       "5                                             Neutral    \n",
       "6                                                Safe    \n",
       "7                                              Unsafe    \n",
       "8                                           Very Safe    \n",
       "9                                           Very Safe    \n",
       "10                                        Very Unsafe    \n",
       "11                                        Very Unsafe    \n",
       "12                                        Very Unsafe    \n",
       "13                                            Neutral    \n",
       "14                                          Very Safe    \n",
       "15                                        Very Unsafe    \n",
       "16                                             Unsafe    \n",
       "17                                        Very Unsafe    \n",
       "18                                        Very Unsafe    \n",
       "19                                            Neutral    \n",
       "\n",
       "   How would you describe the cleanliness in your neighborhood?  \\\n",
       "0                                             Neutral             \n",
       "1                                               Dirty             \n",
       "2                                               Dirty             \n",
       "3                                               Clean             \n",
       "4                                             Neutral             \n",
       "5                                          Very Dirty             \n",
       "6                                             Neutral             \n",
       "7                                               Dirty             \n",
       "8                                               Clean             \n",
       "9                                             Neutral             \n",
       "10                                              Clean             \n",
       "11                                         Very Clean             \n",
       "12                                            Neutral             \n",
       "13                                              Dirty             \n",
       "14                                         Very Dirty             \n",
       "15                                              Dirty             \n",
       "16                                            Neutral             \n",
       "17                                              Dirty             \n",
       "18                                            Neutral             \n",
       "19                                         Very Clean             \n",
       "\n",
       "   How would you rate the availability of amenities in your neighborhood?  \\\n",
       "0                                           Very Poor                       \n",
       "1                                           Very Poor                       \n",
       "2                                             Average                       \n",
       "3                                                Good                       \n",
       "4                                             Average                       \n",
       "5                                           Excellent                       \n",
       "6                                                Poor                       \n",
       "7                                             Average                       \n",
       "8                                           Excellent                       \n",
       "9                                             Average                       \n",
       "10                                            Average                       \n",
       "11                                          Excellent                       \n",
       "12                                               Good                       \n",
       "13                                               Good                       \n",
       "14                                          Excellent                       \n",
       "15                                            Average                       \n",
       "16                                               Poor                       \n",
       "17                                               Good                       \n",
       "18                                          Very Poor                       \n",
       "19                                          Excellent                       \n",
       "\n",
       "   How would you rate the quality of schools in your neighborhood?  \\\n",
       "0                                             Average                \n",
       "1                                                Good                \n",
       "2                                                Poor                \n",
       "3                                                Poor                \n",
       "4                                           Very Poor                \n",
       "5                                           Excellent                \n",
       "6                                           Excellent                \n",
       "7                                           Very Poor                \n",
       "8                                           Very Poor                \n",
       "9                                                Good                \n",
       "10                                          Excellent                \n",
       "11                                          Very Poor                \n",
       "12                                            Average                \n",
       "13                                          Very Poor                \n",
       "14                                               Poor                \n",
       "15                                          Very Poor                \n",
       "16                                               Good                \n",
       "17                                               Good                \n",
       "18                                          Very Poor                \n",
       "19                                               Good                \n",
       "\n",
       "   How would you rate the affordability of housing in your neighborhood?  \\\n",
       "0                                     Very Affordable                      \n",
       "1                                             Neutral                      \n",
       "2                                          Affordable                      \n",
       "3                                          Affordable                      \n",
       "4                                     Very Affordable                      \n",
       "5                                             Neutral                      \n",
       "6                                      Very Expensive                      \n",
       "7                                           Expensive                      \n",
       "8                                          Affordable                      \n",
       "9                                     Very Affordable                      \n",
       "10                                         Affordable                      \n",
       "11                                         Affordable                      \n",
       "12                                          Expensive                      \n",
       "13                                         Affordable                      \n",
       "14                                          Expensive                      \n",
       "15                                    Very Affordable                      \n",
       "16                                            Neutral                      \n",
       "17                                     Very Expensive                      \n",
       "18                                          Expensive                      \n",
       "19                                            Neutral                      \n",
       "\n",
       "   How would you rate the friendliness of neighbors in your neighborhood?  \\\n",
       "0                                     Very Unfriendly                       \n",
       "1                                          Unfriendly                       \n",
       "2                                          Unfriendly                       \n",
       "3                                          Unfriendly                       \n",
       "4                                       Very Friendly                       \n",
       "5                                     Very Unfriendly                       \n",
       "6                                          Unfriendly                       \n",
       "7                                             Neutral                       \n",
       "8                                     Very Unfriendly                       \n",
       "9                                     Very Unfriendly                       \n",
       "10                                    Very Unfriendly                       \n",
       "11                                           Friendly                       \n",
       "12                                         Unfriendly                       \n",
       "13                                      Very Friendly                       \n",
       "14                                           Friendly                       \n",
       "15                                            Neutral                       \n",
       "16                                      Very Friendly                       \n",
       "17                                         Unfriendly                       \n",
       "18                                            Neutral                       \n",
       "19                                            Neutral                       \n",
       "\n",
       "   How satisfied are you with the green spaces in your neighborhood?  \\\n",
       "0                                      Very Satisfied                  \n",
       "1                                             Neutral                  \n",
       "2                                             Neutral                  \n",
       "3                                             Neutral                  \n",
       "4                                   Very Dissatisfied                  \n",
       "5                                        Dissatisfied                  \n",
       "6                                   Very Dissatisfied                  \n",
       "7                                        Dissatisfied                  \n",
       "8                                   Very Dissatisfied                  \n",
       "9                                             Neutral                  \n",
       "10                                          Satisfied                  \n",
       "11                                          Satisfied                  \n",
       "12                                       Dissatisfied                  \n",
       "13                                       Dissatisfied                  \n",
       "14                                       Dissatisfied                  \n",
       "15                                          Satisfied                  \n",
       "16                                       Dissatisfied                  \n",
       "17                                          Satisfied                  \n",
       "18                                     Very Satisfied                  \n",
       "19                                     Very Satisfied                  \n",
       "\n",
       "   How would you rate the noise levels in your neighborhood?  ...  \\\n",
       "0                                          Very Noisy         ...   \n",
       "1                                               Noisy         ...   \n",
       "2                                             Neutral         ...   \n",
       "3                                               Quiet         ...   \n",
       "4                                               Noisy         ...   \n",
       "5                                               Noisy         ...   \n",
       "6                                          Very Quiet         ...   \n",
       "7                                               Noisy         ...   \n",
       "8                                               Quiet         ...   \n",
       "9                                               Noisy         ...   \n",
       "10                                            Neutral         ...   \n",
       "11                                              Noisy         ...   \n",
       "12                                              Noisy         ...   \n",
       "13                                              Quiet         ...   \n",
       "14                                         Very Noisy         ...   \n",
       "15                                              Quiet         ...   \n",
       "16                                         Very Quiet         ...   \n",
       "17                                              Noisy         ...   \n",
       "18                                         Very Noisy         ...   \n",
       "19                                              Quiet         ...   \n",
       "\n",
       "   How would you rate the public services in your neighborhood?  \\\n",
       "0                                                Good             \n",
       "1                                           Excellent             \n",
       "2                                           Very Poor             \n",
       "3                                                Good             \n",
       "4                                           Very Poor             \n",
       "5                                           Excellent             \n",
       "6                                           Very Poor             \n",
       "7                                           Very Poor             \n",
       "8                                                Poor             \n",
       "9                                           Excellent             \n",
       "10                                            Average             \n",
       "11                                          Very Poor             \n",
       "12                                               Good             \n",
       "13                                          Very Poor             \n",
       "14                                               Good             \n",
       "15                                          Excellent             \n",
       "16                                               Good             \n",
       "17                                          Excellent             \n",
       "18                                               Good             \n",
       "19                                          Very Poor             \n",
       "\n",
       "   How would you rate the condition of roads and sidewalks in your neighborhood?  \\\n",
       "0                                             Average                              \n",
       "1                                           Very Poor                              \n",
       "2                                           Very Poor                              \n",
       "3                                                Poor                              \n",
       "4                                           Very Poor                              \n",
       "5                                                Good                              \n",
       "6                                           Very Poor                              \n",
       "7                                                Good                              \n",
       "8                                             Average                              \n",
       "9                                           Very Poor                              \n",
       "10                                          Very Poor                              \n",
       "11                                          Very Poor                              \n",
       "12                                            Average                              \n",
       "13                                               Poor                              \n",
       "14                                          Excellent                              \n",
       "15                                          Very Poor                              \n",
       "16                                            Average                              \n",
       "17                                            Average                              \n",
       "18                                            Average                              \n",
       "19                                               Poor                              \n",
       "\n",
       "   How would you rate the availability of parking in your neighborhood?  \\\n",
       "0                                           Very Poor                     \n",
       "1                                                Good                     \n",
       "2                                           Very Poor                     \n",
       "3                                             Average                     \n",
       "4                                           Very Poor                     \n",
       "5                                           Very Poor                     \n",
       "6                                           Very Poor                     \n",
       "7                                                Poor                     \n",
       "8                                             Average                     \n",
       "9                                             Average                     \n",
       "10                                               Poor                     \n",
       "11                                          Excellent                     \n",
       "12                                          Excellent                     \n",
       "13                                            Average                     \n",
       "14                                               Poor                     \n",
       "15                                               Good                     \n",
       "16                                            Average                     \n",
       "17                                          Excellent                     \n",
       "18                                               Poor                     \n",
       "19                                               Poor                     \n",
       "\n",
       "   How would you rate the access to healthcare in your neighborhood?  \\\n",
       "0                                                Good                  \n",
       "1                                             Average                  \n",
       "2                                           Excellent                  \n",
       "3                                                Good                  \n",
       "4                                             Average                  \n",
       "5                                                Poor                  \n",
       "6                                                Good                  \n",
       "7                                             Average                  \n",
       "8                                           Excellent                  \n",
       "9                                           Excellent                  \n",
       "10                                            Average                  \n",
       "11                                          Excellent                  \n",
       "12                                            Average                  \n",
       "13                                          Excellent                  \n",
       "14                                          Very Poor                  \n",
       "15                                            Average                  \n",
       "16                                          Very Poor                  \n",
       "17                                            Average                  \n",
       "18                                          Excellent                  \n",
       "19                                               Good                  \n",
       "\n",
       "   How would you rate the quality of internet services in your neighborhood?  \\\n",
       "0                                                Good                          \n",
       "1                                             Average                          \n",
       "2                                                Poor                          \n",
       "3                                           Excellent                          \n",
       "4                                           Very Poor                          \n",
       "5                                                Poor                          \n",
       "6                                                Good                          \n",
       "7                                           Very Poor                          \n",
       "8                                                Poor                          \n",
       "9                                           Excellent                          \n",
       "10                                               Poor                          \n",
       "11                                               Good                          \n",
       "12                                            Average                          \n",
       "13                                               Good                          \n",
       "14                                          Very Poor                          \n",
       "15                                          Very Poor                          \n",
       "16                                          Excellent                          \n",
       "17                                          Very Poor                          \n",
       "18                                               Poor                          \n",
       "19                                               Poor                          \n",
       "\n",
       "   How would you rate the variety of restaurants in your neighborhood?  \\\n",
       "0                                           Very Poor                    \n",
       "1                                                Good                    \n",
       "2                                             Average                    \n",
       "3                                                Good                    \n",
       "4                                                Good                    \n",
       "5                                           Excellent                    \n",
       "6                                                Poor                    \n",
       "7                                                Good                    \n",
       "8                                                Good                    \n",
       "9                                           Excellent                    \n",
       "10                                               Poor                    \n",
       "11                                               Poor                    \n",
       "12                                            Average                    \n",
       "13                                               Good                    \n",
       "14                                               Poor                    \n",
       "15                                               Poor                    \n",
       "16                                               Poor                    \n",
       "17                                          Excellent                    \n",
       "18                                            Average                    \n",
       "19                                          Excellent                    \n",
       "\n",
       "   How would you rate the variety of shops in your neighborhood?  \\\n",
       "0                                           Excellent              \n",
       "1                                                Poor              \n",
       "2                                             Average              \n",
       "3                                                Good              \n",
       "4                                             Average              \n",
       "5                                           Excellent              \n",
       "6                                             Average              \n",
       "7                                           Excellent              \n",
       "8                                           Very Poor              \n",
       "9                                           Excellent              \n",
       "10                                            Average              \n",
       "11                                               Good              \n",
       "12                                          Very Poor              \n",
       "13                                               Good              \n",
       "14                                          Excellent              \n",
       "15                                               Good              \n",
       "16                                               Good              \n",
       "17                                               Poor              \n",
       "18                                               Poor              \n",
       "19                                          Excellent              \n",
       "\n",
       "   How would you rate the availability of cultural activities in your neighborhood?  \\\n",
       "0                                             Average                                 \n",
       "1                                                Poor                                 \n",
       "2                                           Excellent                                 \n",
       "3                                                Poor                                 \n",
       "4                                             Average                                 \n",
       "5                                             Average                                 \n",
       "6                                           Very Poor                                 \n",
       "7                                           Excellent                                 \n",
       "8                                                Poor                                 \n",
       "9                                                Poor                                 \n",
       "10                                          Excellent                                 \n",
       "11                                               Poor                                 \n",
       "12                                            Average                                 \n",
       "13                                          Very Poor                                 \n",
       "14                                               Poor                                 \n",
       "15                                               Poor                                 \n",
       "16                                          Excellent                                 \n",
       "17                                               Good                                 \n",
       "18                                          Very Poor                                 \n",
       "19                                               Poor                                 \n",
       "\n",
       "   How would you rate the availability of recreational activities in your neighborhood?  \\\n",
       "0                                             Average                                     \n",
       "1                                             Average                                     \n",
       "2                                             Average                                     \n",
       "3                                           Excellent                                     \n",
       "4                                           Very Poor                                     \n",
       "5                                                Good                                     \n",
       "6                                             Average                                     \n",
       "7                                                Good                                     \n",
       "8                                           Very Poor                                     \n",
       "9                                           Very Poor                                     \n",
       "10                                            Average                                     \n",
       "11                                          Excellent                                     \n",
       "12                                          Excellent                                     \n",
       "13                                          Very Poor                                     \n",
       "14                                            Average                                     \n",
       "15                                            Average                                     \n",
       "16                                               Poor                                     \n",
       "17                                               Poor                                     \n",
       "18                                          Excellent                                     \n",
       "19                                               Poor                                     \n",
       "\n",
       "   How would you rate the public transportation costs in your neighborhood?  \n",
       "0                                      Very Expensive                        \n",
       "1                                             Neutral                        \n",
       "2                                           Expensive                        \n",
       "3                                     Very Affordable                        \n",
       "4                                     Very Affordable                        \n",
       "5                                      Very Expensive                        \n",
       "6                                           Expensive                        \n",
       "7                                          Affordable                        \n",
       "8                                      Very Expensive                        \n",
       "9                                     Very Affordable                        \n",
       "10                                            Neutral                        \n",
       "11                                          Expensive                        \n",
       "12                                         Affordable                        \n",
       "13                                    Very Affordable                        \n",
       "14                                            Neutral                        \n",
       "15                                         Affordable                        \n",
       "16                                         Affordable                        \n",
       "17                                            Neutral                        \n",
       "18                                         Affordable                        \n",
       "19                                          Expensive                        \n",
       "\n",
       "[20 rows x 21 columns]"
      ]
     },
     "execution_count": 65,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2.Data Preparation:\n",
    "\n",
    "- **Stripping Whitespace**: The code strips leading and trailing whitespace from column names using df.columns.str.strip(). This ensures column names are clean and free of extra spaces.\n",
    "\n",
    "- **Storing Original Column Names**: The original column names are stored in original_columns for reference.\n",
    "\n",
    "- **Sanitizing Column Names**: Punctuation is removed from column names, and they are truncated to 31 characters to make them suitable for Excel sheet names. This is done using df.columns.str.replace('[^\\\\s]', '', regex=True).str[:31]."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Strip leading/trailing whitespace from column names\n",
    "df.columns = df.columns.str.strip()\n",
    "\n",
    "# Store original column names\n",
    "original_columns = df.columns.copy()\n",
    "\n",
    "# Remove punctuation from column names for Excel sheet names and truncate to 31 characters\n",
    "sanitized_columns = df.columns.str.replace('[^\\w\\s]', '', regex=True).str[:31]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Create Crosstabs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing column: How satisfied are you with the public transportation in your neighborhood?\n",
      "Processing column: How would you rate the safety in your neighborhood?\n",
      "Processing column: How would you describe the cleanliness in your neighborhood?\n",
      "Processing column: How would you rate the availability of amenities in your neighborhood?\n",
      "Processing column: How would you rate the quality of schools in your neighborhood?\n",
      "Processing column: How would you rate the affordability of housing in your neighborhood?\n",
      "Processing column: How would you rate the friendliness of neighbors in your neighborhood?\n",
      "Processing column: How satisfied are you with the green spaces in your neighborhood?\n",
      "Processing column: How would you rate the noise levels in your neighborhood?\n",
      "Processing column: How would you rate the overall quality of life in your neighborhood?\n",
      "Processing column: How would you rate the public services in your neighborhood?\n",
      "Processing column: How would you rate the condition of roads and sidewalks in your neighborhood?\n",
      "Processing column: How would you rate the availability of parking in your neighborhood?\n",
      "Processing column: How would you rate the access to healthcare in your neighborhood?\n",
      "Processing column: How would you rate the quality of internet services in your neighborhood?\n",
      "Processing column: How would you rate the variety of restaurants in your neighborhood?\n",
      "Processing column: How would you rate the variety of shops in your neighborhood?\n",
      "Processing column: How would you rate the availability of cultural activities in your neighborhood?\n",
      "Processing column: How would you rate the availability of recreational activities in your neighborhood?\n",
      "Processing column: How would you rate the public transportation costs in your neighborhood?\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2658976717.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.\n",
      "  percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n"
     ]
    }
   ],
   "source": [
    "# Create a dictionary to store the crosstabs\n",
    "crosstabs = {}\n",
    "\n",
    "# Specify the constant column name\n",
    "constant_column = 'Where do you live in Boston?'\n",
    "\n",
    "# Iterate over each column in the DataFrame (excluding the constant column)\n",
    "for column in df.columns:\n",
    "    if column != constant_column:\n",
    "        print(f\"Processing column: {column}\")\n",
    "\n",
    "        # Create a crosstab for the current column against the constant column\n",
    "        crosstab = pd.crosstab(index=df[column], columns=df[constant_column])\n",
    "\n",
    "        # Calculate percentages for each cell based on the column total\n",
    "        percentage_crosstab = crosstab.div(crosstab.sum(axis=0), axis=1) * 100\n",
    "\n",
    "        # Round the percentage values\n",
    "        percentage_crosstab = percentage_crosstab.round(2)\n",
    "\n",
    "        # Add the '%' symbol to the percentage values\n",
    "        percentage_crosstab = percentage_crosstab.applymap(lambda x: f'{x:.2f}%')\n",
    "\n",
    "        # Rename the percentage columns\n",
    "        percentage_crosstab = percentage_crosstab.rename(columns=lambda x: x + ' %')\n",
    "\n",
    "        # Combine the original crosstab and the percentage crosstab\n",
    "        combined_crosstab = pd.concat([crosstab, percentage_crosstab], axis=1)\n",
    "\n",
    "        # Rearrange the columns so that each neighborhood column is followed by its percentage column\n",
    "        ordered_columns = []\n",
    "        for col in crosstab.columns:\n",
    "            ordered_columns.append(col)\n",
    "            ordered_columns.append(col + ' %')\n",
    "        combined_crosstab = combined_crosstab[ordered_columns]\n",
    "\n",
    "        # Store the combined crosstab in the dictionary\n",
    "        crosstabs[column] = combined_crosstab\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th>Where do you live in Boston?</th>\n",
       "      <th>Back Bay</th>\n",
       "      <th>Back Bay %</th>\n",
       "      <th>Beacon Hill</th>\n",
       "      <th>Beacon Hill %</th>\n",
       "      <th>Downtown</th>\n",
       "      <th>Downtown %</th>\n",
       "      <th>North End</th>\n",
       "      <th>North End %</th>\n",
       "      <th>South End</th>\n",
       "      <th>South End %</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>How would you rate the public transportation costs in your neighborhood?</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Affordable</th>\n",
       "      <td>1</td>\n",
       "      <td>20.00%</td>\n",
       "      <td>1</td>\n",
       "      <td>33.33%</td>\n",
       "      <td>2</td>\n",
       "      <td>50.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>1</td>\n",
       "      <td>14.29%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Expensive</th>\n",
       "      <td>1</td>\n",
       "      <td>20.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>1</td>\n",
       "      <td>100.00%</td>\n",
       "      <td>2</td>\n",
       "      <td>28.57%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Neutral</th>\n",
       "      <td>1</td>\n",
       "      <td>20.00%</td>\n",
       "      <td>1</td>\n",
       "      <td>33.33%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>2</td>\n",
       "      <td>28.57%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Very Affordable</th>\n",
       "      <td>1</td>\n",
       "      <td>20.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>1</td>\n",
       "      <td>25.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>2</td>\n",
       "      <td>28.57%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Very Expensive</th>\n",
       "      <td>1</td>\n",
       "      <td>20.00%</td>\n",
       "      <td>1</td>\n",
       "      <td>33.33%</td>\n",
       "      <td>1</td>\n",
       "      <td>25.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "      <td>0</td>\n",
       "      <td>0.00%</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Where do you live in Boston?                        Back Bay Back Bay %  \\\n",
       "How would you rate the public transportation co...                        \n",
       "Affordable                                                 1     20.00%   \n",
       "Expensive                                                  1     20.00%   \n",
       "Neutral                                                    1     20.00%   \n",
       "Very Affordable                                            1     20.00%   \n",
       "Very Expensive                                             1     20.00%   \n",
       "\n",
       "Where do you live in Boston?                        Beacon Hill Beacon Hill %  \\\n",
       "How would you rate the public transportation co...                              \n",
       "Affordable                                                    1        33.33%   \n",
       "Expensive                                                     0         0.00%   \n",
       "Neutral                                                       1        33.33%   \n",
       "Very Affordable                                               0         0.00%   \n",
       "Very Expensive                                                1        33.33%   \n",
       "\n",
       "Where do you live in Boston?                        Downtown Downtown %  \\\n",
       "How would you rate the public transportation co...                        \n",
       "Affordable                                                 2     50.00%   \n",
       "Expensive                                                  0      0.00%   \n",
       "Neutral                                                    0      0.00%   \n",
       "Very Affordable                                            1     25.00%   \n",
       "Very Expensive                                             1     25.00%   \n",
       "\n",
       "Where do you live in Boston?                        North End North End %  \\\n",
       "How would you rate the public transportation co...                          \n",
       "Affordable                                                  0       0.00%   \n",
       "Expensive                                                   1     100.00%   \n",
       "Neutral                                                     0       0.00%   \n",
       "Very Affordable                                             0       0.00%   \n",
       "Very Expensive                                              0       0.00%   \n",
       "\n",
       "Where do you live in Boston?                        South End South End %  \n",
       "How would you rate the public transportation co...                         \n",
       "Affordable                                                  1      14.29%  \n",
       "Expensive                                                   2      28.57%  \n",
       "Neutral                                                     2      28.57%  \n",
       "Very Affordable                                             2      28.57%  \n",
       "Very Expensive                                              0       0.00%  "
      ]
     },
     "execution_count": 67,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "crosstabs[column] "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Writing to Excel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:6: SyntaxWarning: invalid escape sequence '\\w'\n",
      "<>:6: SyntaxWarning: invalid escape sequence '\\w'\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2794199723.py:6: SyntaxWarning: invalid escape sequence '\\w'\n",
      "  sheet_name = re.sub('[^\\w\\s]', '', column)[:31]\n",
      "/var/folders/0g/n12bjh5j5rz4c440njxzw_sw0000gn/T/ipykernel_1946/2794199723.py:6: SyntaxWarning: invalid escape sequence '\\w'\n",
      "  sheet_name = re.sub('[^\\w\\s]', '', column)[:31]\n"
     ]
    },
    {
     "ename": "OSError",
     "evalue": "[Errno 30] Read-only file system: 'questions_crosstabs.xlsx'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[79], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Save the crosstabs to an Excel file\u001b[39;00m\n\u001b[1;32m      2\u001b[0m file_path \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mquestions_crosstabs.xlsx\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[43mpd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mExcelWriter\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mengine\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mxlsxwriter\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mas\u001b[39;00m writer:\n\u001b[1;32m      4\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m column, crosstab \u001b[38;5;129;01min\u001b[39;00m crosstabs\u001b[38;5;241m.\u001b[39mitems():\n\u001b[1;32m      5\u001b[0m         \u001b[38;5;66;03m# Sanitize the sheet name\u001b[39;00m\n\u001b[1;32m      6\u001b[0m         sheet_name \u001b[38;5;241m=\u001b[39m re\u001b[38;5;241m.\u001b[39msub(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m[^\u001b[39m\u001b[38;5;124m\\\u001b[39m\u001b[38;5;124mw\u001b[39m\u001b[38;5;124m\\\u001b[39m\u001b[38;5;124ms]\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m'\u001b[39m, column)[:\u001b[38;5;241m31\u001b[39m]\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/io/excel/_xlsxwriter.py:204\u001b[0m, in \u001b[0;36mXlsxWriter.__init__\u001b[0;34m(self, path, engine, date_format, datetime_format, mode, storage_options, if_sheet_exists, engine_kwargs, **kwargs)\u001b[0m\n\u001b[1;32m    201\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m mode \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[1;32m    202\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAppend mode is not supported with xlsxwriter!\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m--> 204\u001b[0m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[38;5;21;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\n\u001b[1;32m    205\u001b[0m \u001b[43m    \u001b[49m\u001b[43mpath\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    206\u001b[0m \u001b[43m    \u001b[49m\u001b[43mengine\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mengine\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    207\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdate_format\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdate_format\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    208\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdatetime_format\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdatetime_format\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    209\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmode\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    210\u001b[0m \u001b[43m    \u001b[49m\u001b[43mstorage_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstorage_options\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    211\u001b[0m \u001b[43m    \u001b[49m\u001b[43mif_sheet_exists\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mif_sheet_exists\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    212\u001b[0m \u001b[43m    \u001b[49m\u001b[43mengine_kwargs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mengine_kwargs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    213\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    215\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    216\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_book \u001b[38;5;241m=\u001b[39m Workbook(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handles\u001b[38;5;241m.\u001b[39mhandle, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mengine_kwargs)\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/io/excel/_base.py:1246\u001b[0m, in \u001b[0;36mExcelWriter.__init__\u001b[0;34m(self, path, engine, date_format, datetime_format, mode, storage_options, if_sheet_exists, engine_kwargs)\u001b[0m\n\u001b[1;32m   1242\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handles \u001b[38;5;241m=\u001b[39m IOHandles(\n\u001b[1;32m   1243\u001b[0m     cast(IO[\u001b[38;5;28mbytes\u001b[39m], path), compression\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcompression\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;28;01mNone\u001b[39;00m}\n\u001b[1;32m   1244\u001b[0m )\n\u001b[1;32m   1245\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(path, ExcelWriter):\n\u001b[0;32m-> 1246\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handles \u001b[38;5;241m=\u001b[39m \u001b[43mget_handle\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1247\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpath\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstorage_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstorage_options\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mis_text\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\n\u001b[1;32m   1248\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1249\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_cur_sheet \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m   1251\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m date_format \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/io/common.py:882\u001b[0m, in \u001b[0;36mget_handle\u001b[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)\u001b[0m\n\u001b[1;32m    873\u001b[0m         handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mopen\u001b[39m(\n\u001b[1;32m    874\u001b[0m             handle,\n\u001b[1;32m    875\u001b[0m             ioargs\u001b[38;5;241m.\u001b[39mmode,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    878\u001b[0m             newline\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    879\u001b[0m         )\n\u001b[1;32m    880\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    881\u001b[0m         \u001b[38;5;66;03m# Binary mode\u001b[39;00m\n\u001b[0;32m--> 882\u001b[0m         handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mhandle\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mioargs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    883\u001b[0m     handles\u001b[38;5;241m.\u001b[39mappend(handle)\n\u001b[1;32m    885\u001b[0m \u001b[38;5;66;03m# Convert BytesIO or file objects passed with an encoding\u001b[39;00m\n",
      "\u001b[0;31mOSError\u001b[0m: [Errno 30] Read-only file system: 'questions_crosstabs.xlsx'"
     ]
    }
   ],
   "source": [
    "# Save the crosstabs to an Excel file\n",
    "file_path = 'questions_crosstabs.xlsx'\n",
    "with pd.ExcelWriter(file_path, engine='xlsxwriter') as writer:\n",
    "    for column, crosstab in crosstabs.items():\n",
    "        # Sanitize the sheet name\n",
    "        sheet_name = re.sub('[^\\w\\s]', '', column)[:31]\n",
    "        # Write each crosstab to a separate sheet in the Excel file\n",
    "        crosstab.to_excel(writer, sheet_name=sheet_name, startrow=4)  # start writing from the fifth row\n",
    "        \n",
    "        # Get the XlsxWriter workbook and worksheet objects\n",
    "        workbook = writer.book\n",
    "        worksheet = writer.sheets[sheet_name]\n",
    "        \n",
    "        # Add some formats\n",
    "        header_format = workbook.add_format({'bold': True, 'text_wrap': True, 'align': 'center', 'valign': 'top', 'bg_color': '#D3D3D3', 'border': 1})\n",
    "        cell_format = workbook.add_format({'border': 1})\n",
    "        \n",
    "        # Write the original column name on the first row\n",
    "        worksheet.write(0, 0, column, header_format)\n",
    "        \n",
    "        # Set the column width\n",
    "        for col_num, value in enumerate(crosstab.columns):\n",
    "            max_len = max(\n",
    "                crosstab.index.astype(str).str.len().max(), \n",
    "                len(str(value))\n",
    "            ) + 2\n",
    "            worksheet.set_column(col_num + 1, col_num + 1, max_len)  # Columns are 0-indexed, so adding 1\n",
    "\n",
    "        # Set the header format for the crosstab\n",
    "        for col_num, value in enumerate(crosstab.columns):\n",
    "            worksheet.write(4, col_num + 1, value, header_format)  # Writing headers with format\n",
    "        \n",
    "        for row_num, value in enumerate(crosstab.index):\n",
    "            worksheet.write(row_num + 5, 0, value, header_format)  # Writing row headers with format\n",
    "\n",
    "        # Write the data with the cell border format\n",
    "        for row_num, row_data in enumerate(crosstab.values):\n",
    "            for col_num, cell_data in enumerate(row_data):\n",
    "                worksheet.write(row_num + 5, col_num + 1, cell_data, cell_format)  # Writing data with border format\n",
    "\n",
    "print(\"Crosstabs have been saved to 'questions_crosstabs.xlsx'\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
